Display more detailed leaderboard on review page
TreeHacks/root pull request #150
Opened 2019-11-10 07:57 UTC by MYKatz

Added a separate leaderboard, counting the last seven days' worth of reviews. "fix" for #148 

![screenshot-localhost_9000-2019 11 09-23_56_29](https://user-images.githubusercontent.com/23515048/68540833-ab9fdd00-034c-11ea-9438-bb085e15a757.png)

2019-11-10 07:59 UTC, MYKatz commented
Oh fuck gotta update some tests

2019-11-10 07:59 UTC, theopolisme commented
This is gonna be awesome!!! :D Can we do a single table with two columns though (maybe something like "all" and "7d")?

2019-11-10 08:01 UTC, MYKatz commented
> This is gonna be awesome!!! :D Can we do a single table with two columns though (maybe something like "all" and "7d")?

That's a great idea. Will do

2019-11-10 09:05 UTC, MYKatz commented
Alright @theopolisme, looks to be working nicely now on my end.
![screenshot-localhost_9000-2019 11 10-00_56_20](https://user-images.githubusercontent.com/23515048/68541586-27eaee00-0356-11ea-9824-408224a89746.png)

2019-11-10 22:32 UTC, theopolisme requested changes
Awesome!! Minor tweaks and then let's get this merged ❤️

2019-11-10 22:32 UTC, theopolisme commented on src/Review/Review.tsx
> +								<th></th>
Let's make a header "Reviewer"? To add some visual balance

2019-11-10 22:32 UTC, theopolisme commented on backend/routes/user_review.ts
> +                $size: { $filter: { input: "$dates", as: "d", cond: { $gt: [ "$$d", new Date(new Date().setDate(new Date().getDate()-7)) ] } } }
Can't you remove this `new Date(new Date().setDate(new Date().getDate()-7))` and simply use `d` (defined above) instead? (Maybe you were going for that but didn't finish refactoring?)

2019-11-11 05:58 UTC, MYKatz commented
@theopolisme made the tweaks. Next time I'll work on being more careful lol

2019-11-11 06:03 UTC, merged

2019-11-11 06:03 UTC, theopolisme commented
🎉 Awesome work!!!