fixed wordCount
TreeHacks/root pull request #287
Opened 2024-11-02 04:47 UTC by amichaelyu

The regex for the current wordCount is implemented incorrectly.

2024-11-02 05:55 UTC, amichaelyu commented
@connorff

2024-11-03 05:07 UTC, connorff requested changes
Hey Michael, thank you for this pull request! Just some minor comments but, again, appreciate it :)

2024-11-03 05:07 UTC, connorff commented on src/FormPage/FormPage.tsx
> +  const wordCount = value.split(/[\s]+/).filter(function (el) {return el !== '';}).length;
Sometimes `value` is undefined (user hasn't filled out a field), so we still need the ternary check.

Also, for the `filter` function, we could rewrite it as `.filter(el => el !== '')` to reduce the line length.

2024-11-03 05:07 UTC, connorff commented on src/FormPage/FormPage.tsx
> +      if (formData[key] && formData[key].split(/[\s]+/).filter(function (el) {return el !== '';}).length > wordCount) {
Same thing in this `filter`: `.filter(el => el !== '')`

2024-11-03 22:48 UTC, connorff approved these changes
Thanks!

2024-11-03 22:48 UTC, merged