Root style changes
TreeHacks/root pull request #94
Opened 2019-10-22 21:44 UTC by lucaspauker

- Add icons on main page
closes #73

- Fix navbar (make it look like `website`)
closes #92

2019-10-22 22:45 UTC, theopolisme requested changes
This is awesome!!
1. Can we change it so that the navbar is pure white #fff?
2. Also, related, all the text fields/text areas/containers (e.g. the box on the homepage/travel page) should be #fff background as well. I think this way we'll keep all the content much better accented.
3. In navbar, a little more padding between the logo tree and the text (like how it is on https://treehacks.com/) would be great
4. Feels a little weird that drone is going side to side. Maybe should be up/down? Idk though let's discuss in person

Thank you!!!

2019-10-22 23:26 UTC, lucaspauker commented
The white-on-pink looks a bit funky imo (maybe look better if colors were more distinct?), but it definitely stands out better.

2019-10-23 00:44 UTC, theopolisme commented
Maybe I'm tripping but looks like there's a pink line under the logo - right above the end of navbar/above the shadow?
<img width="234" alt="Screen Shot 2019-10-22 at 5 43 13 PM" src="https://user-images.githubusercontent.com/1410202/67346411-865d4300-f4f3-11e9-81ec-9b5e669282a8.png">

2019-10-23 02:19 UTC, theopolisme commented on src/common/Aesthetics.scss
> +      animation-name: leftright;
```suggestion
      animation-name: updown;
```

2019-10-23 05:06 UTC, theopolisme commented
@epicfaace looks like snapshots are still failing? would be great to merge asap ❤️

2019-10-23 20:54 UTC, merged